### ISSUE TITLE
Set G3_USING_UNITY compiler flag by default

### ISSUE THREAD

**Issue by rhys-vdw** [ViRGIS-Team/ViRGiS-Geometry#4]
Given this is a UPM form of G3, it seems like this should just on by default.
<https://github.com/gradientspace/geometry3Sharp/blob/79829341d6c225375128c32cd4720dd48f970c6e/mesh_generators/MeshGenerators.cs#L3-L5>

Should be as simple as adding this to the asmdef:
![image](https://user-images.githubusercontent.com/822105/229422941-0c630bc3-0a0e-42a5-92c2-a6249be884da.png)

Happy to make a PR

**Comment by runette** [comment]
Sorry for the delay in responding - we have been focussed on other things and leaving this library to fed for itself.

You are very correct - and this is fixed in https://github.com/ViRGIS-Team/ViRGiS-Geometry/commit/56acb2b4811d33eef73fe11e2a742d1800bd9580.

This will be released as version 3.0.0 which is also coming out under the new name

**Comment by rhys-vdw** [comment]
Eyy, package being supported. Cool. There's actually a bunch of stuff in this lib that could be improved. I'll likely make some contributions in future if we keep using it.

**Comment by rhys-vdw** [comment]
So you've dropped support for non-Unity projects? https://github.com/ViRGIS-Team/ViRGiS-Geometry/pull/7/files#diff-570a7ea62ee97dede5f7829ec749d06c06c306e0f35db51025682ea92f09ca3dL36

**Comment by runette** [comment]
Yes.

This form of the library is Unity focused and there are some very Unity
focused changes coming.

Is that a problem?

**Comment by rhys-vdw** [comment]
Oh no, I was just thinking maybe ultimately Vector3f etc could be replaced with the native types if you want to take that route.

**Comment by runette** [comment]
Too much work and too many complications. We are going with the "improving the implicit conversions" route.

The original g3 repo has been shuttered - there is another repo (g4) that is working as the main replacement in the "generalist" paradigm. We want to focus on something that has value for Unity.

**Comment by rhys-vdw** [comment]
Sounds great. :-)
